services:
  backend:
    image: php:8.4.7-apache
    container_name: php_apache
    ports:
      - "5000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
